name: my_pos
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

#--------------- PACKAGES ------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.18.1
  logger: ^2.5.0
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.1
  smooth_page_indicator: ^1.1.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.2

  # State Management
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  get: ^4.7.2

  # Product Specific
  readmore: ^2.2.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  capped_progress_indicator: ^0.0.2
  connectivity_plus: ^6.1.3
  fl_chart: ^0.71.0
  flutter_dotenv: ^5.2.1
  syncfusion_flutter_pdf: ^29.1.38
  flutter_markdown: ^0.7.7

  # Database
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7

#--------------- ./ PACKAGES END ------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.14.3

  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.jpg"

flutter:
  uses-material-design: true
  assets:
    - .env
    #--------------- LOCAL ASSETS ------------------#
    - assets/
  # - assets/icons/brands/
  # - assets/images/content/
  # - assets/images/banners/
  # - assets/images/reviews/
  # - assets/images/products/
  # - assets/icons/categories/
  # - assets/images/animations/
  # - assets/icons/payment_methods/
  # - assets/images/on_boarding_images/

  #--------------- LOCAL FONTS ------------------#
  #fonts:
  # - family: Poppins
  #   fonts:
  #     - asset: assets/fonts/Poppins-Light.ttf
  #       weight: 300
  #     - asset: assets/fonts/Poppins-Regular.ttf
  #       weight: 400
  #     - asset: assets/fonts/Poppins-Italic.ttf
  #       style: italic
  #     - asset: assets/fonts/Poppins-Medium.ttf
  #       weight: 500
  #     - asset: assets/fonts/Poppins-MediumItalic.ttf
  #       weight: 500
  #       style: italic
  #     - asset: assets/fonts/Poppins-SemiBold.ttf
  #       weight: 600
  #     - asset: assets/fonts/Poppins-Bold.ttf
  #       weight: 800
